import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { poetsenOne } from "@/lib/fonts";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Martha's Article",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${poetsenOne.variable} min-h-screen`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
